server:
  port: 8080

security:
  oauth2:
    resource:
      jwt:
        key-value: mlnx

org:
  shan:
    security:
      app:
        jwtSigneKey: mlnx     # jwt 加密的签名秘钥

logging:
  level:
    org.shan: debug
    com.mlnx: debug
    org.springframework.security: info

spring:
  datasource:
    url: jdbc:mysql://192.168.10.128:3306/smart_user?useUnicode:true&characterEncoding:utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
