server:
  port: 8082

logging:
  level:
    com.mlnx: debug
    com.shan: debug


org:
  shan:
    security:
      app:
        joinResource: false   # 是否在认证服务中加入资源服务，当认证服务有其他URL需要访问需要加入
        jwtSigneKey: mlnx     # jwt 加密的签名秘钥
        tokenStore: JWT          # 设置token存储的位置
        clients:              # 设置client
          -
            clientId: mlnx
            clientSecret: medgen2011
spring:
  datasource:
    url: jdbc:mysql://192.168.10.128:3306/smart_user?useUnicode:true&characterEncoding:utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
