server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlnx_smart_hospital?useUnicode:true&characterEncoding:utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 3
    host: 127.0.0.1
    port: 12345
logging:
  level:
    com.mlnx: debug
    org.shan: debug
#    org.springframework: debug
#    org.apache: debug
#debug: true

